### PR TITLE
added the changes from  @Tiakin Tiakin 

### PR DESCRIPTION
**Pull request by Haeherfeder**
please answer, if you are okay with the merge

### CODE REVIEW

**Comment by Tiakin** [comment]
I've made some big change (my version of Towny was in french) so I've made a support for other lang. now if you want you can merge 😄

**Comment by Haeherfeder** [comment]
didn't get a notification

**Comment by Haeherfeder** [comment]
still allowed to merge?

**Comment by Tiakin** [comment]
yes !

**Comment by Haeherfeder** [comment]
is merged, so my pull request is updated

**Pull request merged**
